### ISSUE TITLE
Error 22 when using encrypting Lenovo unit

### ISSUE THREAD

**Issue by 13tatavo** [square/luks2crypt#68]
Hi,

I'm getting the error 22 when testing on Ubuntu OS 20.04 LTS with a VM and a Lenovo t460s.  I'm trying to understand the error and looking for support and location of the logs to read.

Running the command"

`luks2crypt postimaging --luksdevice "/dev/nvm0n1p5" --cryptserver "https://crypt.co.company.com"`

Output with error:

```
2021/08/13 12:00:00 {SerialNum:PC12345 Hostname:lxu:pc12345 username:test}
2021/08/13 12:00:00  generated new random password
error setting escrow passphrase: crypt_load returned error with code -22
```

**Comment by derektamsen** [comment]
@13tatavo Usually that error happens when there is a library version mismatch between `luks2crypt` and the luks header on the device. What version of luks was `/dev/nvm0n1p5` encrypted with? You can check the version with `sudo cryptsetup luksDump /dev/nvm0n1p5 | grep Version`

`luks2crypt` should default to version 2 but you can override it by including `--luksversion 1` if the device was formated with a version 1 luks header.

You may also have an error 22 because you are missing the `--currentpassword "<password_to_replace>"` luks2crypt option. The password specified for this flag will be replaced with a randomly generated password and escrowed to `https://crypt.co.company.com`.

**Comment by 13tatavo** [comment]
I looked more into this with your suggestions and realize I didn't enable Luks at the beginning of the Ubuntu setup. I erased the machine and enable it and was able to get luks2crypt to work.

I do have other questions that maybe you can help with:
- Is there a way to enable Luks without having to erase the drive and start new?

- After encrypting the drive is there a way to allow a user to have their own password and also the random generated password that luks2crypt as options to login, this will be something similar to FileVault on macOS? I prefer not to have to give the random generate password as the only login password for users.
   
- Can luks2crypt automatically select the —luksdevice that needs to be encrypted or does it always need to be defined? If it needs to be define any suggestions in how to script this so it can be automated?

**Comment by derektamsen** [comment]
Great! Glad it worked.

Sure!

> Is there a way to enable Luks without having to erase the drive and start new?

The luks project states there is not really a direct path to simply encrypt the partition in the same way macos can. According to stackoverflow their might be a way, [but it looks a little involved](https://unix.stackexchange.com/a/584275). The comment following the suggestion of how you could convert a volume suggests not to convert the partition. I also would follow that advice and not encrypt an existing partition and instead opt for a fresh partition that is encrypted from the beginning.

> After encrypting the drive is there a way to allow a user to have their own password and also the random generated password that luks2crypt as options to login, this will be something similar to FileVault on macOS? I prefer not to have to give the random generate password as the only login password for users.

Luks supports up to 7 additional keys (8 slots total) which can be used to decrypt the drive. `luks2crypt` was designed to generate an escrowed recovery key which we definitely do not expect the user of the system to use to unlock the device. You can add additional keys to the drive with `sudo cryptsetup luksAddKey <dev_path_to_crypt_device>`. You will then be prompted for an existing passphrase for the device and asked for the additional passphrase you would like to add. Now both the random passphrase and the additional passphrase can unlock the device.

> Can luks2crypt automatically select the —luksdevice that needs to be encrypted or does it always need to be defined? If it needs to be define any suggestions in how to script this so it can be automated?

`luks2crypt` does not currently have the ability to autoselect the encrypted device. At the time the project was created this was decided out of caution since the system could have additional encrypted devices connected. You can see the device filesystem types with `lsblk`. You should be able to grep the output to get the encrypted device with something like `lsblk -flp -o NAME,FSTYPE | grep crypto_LUKS`, then use the output in a script with `luks2crypt`

**Comment by 13tatavo** [comment]
Thanks for the information.

I will write a script to see if I can automate some of it and share my script later here for others if they want it.

**Comment by derektamsen** [comment]
You're welcome! Thanks! Much appreciated

**Comment by 13tatavo** [comment]
Adding script to check for Luks enable partition and requesting user password to add as an approve login passphrase at device startup. May still need some work to check for errors, but I think is a good start.

If anybody wants to use it feel free. 

```
#!/bin/bash

# This script has been developed to use luks2crypt to encrypt the drive on Linux devices using Luks. Encryption key will be store in Corp Crypt Server.
# More info of luks2crypt project can be found at https://github.com/square/luks2crypt.
# Created 08/17/2021 by Gustavo Diaz-Anglero
# Last edited:
# Version 1

###################### Requirements ######################
# Use for pop up notification to request user and Crypt Server password
sudo apt install kdialog -y

###################### Variables ######################

# Gets Luks Device info
LuksLocalDevice=$(lsblk -flp -o NAME,FSTYPE | grep crypto_LUKS | awk '{print $1}')

# Path to luks2crypt
pathL2C='/usr/local/bin/luks2crypt'

###################### Functions ######################

### This function setup luks2crypt to create random passphrase and save in crypt server ###
SetLuks2Crypt ()
{
# Request user passphrase variables
userPassword=$(kdialog --password "Please enter your local account login passphrase: ")

# Run luks2crypt commands
sudo $pathL2C postimaging \
  --luksdevice "$LuksLocalDevice" \
  --currentpassword "$userPassword" \
  --cryptserver "crypt.corp.com"
}

### This function adds user passphrase as an allow password to login at startup. ###

AddUserPassphrase ()
{
# Request user passphrase variables
cryptPassword=$(kdialog --password "Please enter the Crypt Server key passphrase: ")

# Add current user password to Luks using crypt setup luksAddKey command
printf "$cryptPassword" | tee crypt_passphrase
printf "$userPassword" | tee user_passphrase
chmod 400 crypt_passphrase
chmod 400 user_passphrase
sudo cryptsetup luksAddKey --key-file ./crypt_passphrase "$LuksLocalDevice" ./user_passphrase
unlink crypt_passphrase
unlink user_passphrase

# Message to user informing of completion.
kdialog --msgbox "User encryption passphrase has been added to login information.\nRestart device and login with user credentials to confirm."
}

###################### Start of Script ####################

# Identifies if Luks partition exists. If yes, it will run luks2crypt.

if [ -z "$LuksLocalDevice" ]; then
echo "No partition is Luks enabled. Unable to add encryption key to Corp IT database."
kdialog --error "No partition is Luks enabled. Unable to add encryption key to Corp IT database."
else
echo "Partition $LuksLocalDevice is Luks enabled, adding encryption key to Corp IT database."
SetLuks2Crypt
sleep 5
AddUserPassphrase
fi

exit 0
```

**Comment by derektamsen** [comment]
Thank you!
